application: screentxt
version: 3
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /static
  static_dir: static

- url: /flowers
  static_dir: flowers

- url: /.*
  script: main.py

